# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graph_test3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftChart', '~> 1.0'
  # Pods for graph_test3

  target 'graph_test3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'graph_test3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
